name: Deploy Streamlit App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Deploy Streamlit App
        env:
          OPENAI_API_KEY: ${{ secrets.YOUR_OPENAI_API_KEY_HERE }}
          SYSTEM_MESSAGE: ${{ secrets.SYSTEM_MESSAGE }}
        run: |
          streamlit run test_v2.py
